" Vim configuration file by Martin Lundberg <martin.lundberg@gmail.com>

" Plugins ------------------------------------------------------------------- {{{

call plug#begin('~/.vim/bundle')

Plug 'git@github.com:marlun/vim-marlun.git'
Plug 'git@github.com:marlun/vim-starwars.git'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-scriptease'
Plug 'tpope/vim-fugitive'
Plug 'bronson/vim-trailing-whitespace'
Plug 'AndrewRadev/splitjoin.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'sukima/xmledit', { 'for': ['html', 'smarty'] }
Plug 'pgdouyon/vim-niffler'
Plug 'scrooloose/syntastic'
Plug 'SirVer/ultisnips'
Plug 'ludovicchabant/vim-gutentags'
Plug 'Shougo/echodoc'
Plug 'regedarek/ZoomWin'
Plug 'vimwiki/vimwiki', { 'branch': 'dev' }

if has('lua') && has('patch-7.3.885')
	Plug 'Shougo/neocomplete'
	Plug 'Shougo/vimproc.vim', { 'do': 'make' }
else
	Plug 'Shougo/neocomplcache.vim'
endif


call plug#end()

" }}}
" General ------------------------------------------------------------------ {{{

" Enable syntax highlighting and choose colorscheme
syntax on

" Load my own colorscheme if available but fallback
" to one that comes with vim
if findfile('colors/leya.vim', &rtp) != ''
	colorscheme leya
elseif findfile('colors/darth.vim', &rtp) != ''
	colorscheme darth
else
	colorscheme delek
endif

" Make sure vim uses UTF-8
set encoding=utf-8

" Make the unnamed register the "* register
set clipboard=unnamed

" Don't save swap-files for recovery
" TODO evaulate if I should remove this
set noswapfile

" Move vim backup files
set directory=~/tmp,/var/tmp,/tmp

" To make it easier to search for things I make vim ignore case except when
" the search pattern contains upper case characters
set ignorecase smartcase

" Enable an improved command completion menu
set wildmenu
set wildmode=full
set wildignorecase
set wildignore+=DS_Store,*/node_modules/*,*/smarty/*,*/tiny_mce/*,*/bower_components/*

" Do upward search for tags file
set tags=./tags;,tags;

" Try safe (:h secure) source of project specific .vimrc file
set exrc
set secure

" Add swedish as a recognized language when spellchecking
set spelllang=en,sv

" }}}
" Interface ---------------------------------------------------------------- {{{

" Allow putting buffers in the background
set hidden

" Allways show the mode that vim is in
set noshowmode

" Show partial commands as you type them.
set showcmd

" Always show a statusline
set laststatus=2

" Tell vim to use all abbrevations when showing messages
set shortmess+=a

" Don't highlight very long lines
set synmaxcol=256

" Don't redraw while executing macros, registers, etc.
set lazyredraw

" Highlight search matches and use incremental search
set hlsearch
set incsearch

" Make the statusline a lot more useful
set statusline=%f " Filename
set statusline+=\ %m%r%w " Modified, Readonly and Preview flags
set statusline+=%= " Switch to right side
silent set statusline+=%{fugitive#head()}
set statusline+=\ [
set statusline+=%Y " File type
set statusline+=/%{&ff} " File format
set statusline+=/%{(&fenc==\"\"?&enc:&fenc)} " File encoding
set statusline+=]
set statusline+=[%v,%l/%L] " Cursor position

" Makes it possible to have different cursor types for different modes.
if exists('$TMUX')
	let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
	let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
elseif !has("gui_running")
	let &t_SI = "\<Esc>]50;CursorShape=1\x7"
	let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" }}}
" Editor ------------------------------------------------------------------- {{{

" In vi the backspace key could normally only delete the text inserted in the
" current edit session. I want the backspace key to be able to remove
" everything so I add everything (see :h 'backspace')
set backspace+=indent,eol,start

" Disable line-wrapping
set nowrap

" Make a tab be 4 spaces both for read and when editing. Read about
" 'softtabstop' to know what I mean. Set indentation to the same.
let s:tabwidth = 2
let &tabstop = s:tabwidth
let &softtabstop = s:tabwidth
let &shiftwidth = s:tabwidth

" Tab in front of a line inserts blanks according to 'shiftwidth'
set smarttab

" Copy the indent from the current line when starting a new
set autoindent

" Characters to use in 'list' mode
if has('patch-7.4.710')
	set listchars=tab:▸\ ,trail:·,eol:¬,space:·
else
	set listchars=tab:▸\ ,trail:·,eol:¬
endif

" Ctrl-A over 07 incmrements to 08
set nrformats-=octal

" Where it makes sense, remove comment leader when joining lines
if v:version >= 704
	set formatoptions+=j
endif

" Use ag to grep if available
" if executable('ag')
" 	set grepprg=ag\ --nogroup\ --nocolor\ --column
" endif

" }}}
" Functions --------------------------------------------------------------- {{{

" }}}
" Mappings & Abbrevations ------------------------------------------------ {{{

" Stupid fingers
iabbrev paied paid

" Best damn mapleader in the world: SPACE!
let mapleader=' '

nnoremap <silent> <c-l> :nohlsearch<CR>
nnoremap <silent> <leader>- :set nolist!<CR>
nnoremap <silent> <leader>W :echo ":w !sudo tee %"<CR>

" Uppercase the current word in insert mode
inoremap <c-^> <ESC>vbUgi

" On Swedish keyboards the [ and ] keys are not as easy to press as on
" american layouts and if you want to prsss the Ctrl-], Ctrl-[ and Ctrl-\
" you'll have to press the following combinations:
"
" Ctrl-] = Ctrl-å
" Ctrl-[ = Ctrl-ä
" Ctrl-\ = Ctrl-ö
"
" To make it more saner (I think) I also map the swedish keys to their
" corresponding keys without the ctrl key.
nmap å ]
nmap ä [
nmap ö \
omap å ]
omap ä [
omap ö \
xmap å ]
xmap ä [
xmap ö \

" The second lines in the following mappings is for iTerm2 but for them to work
" you need to create a mapping in iterm too so that it sends the correct escape
" sequences. Read more here:
" https://groups.google.com/d/msg/iterm2-discuss/VEiCSc5LCIs/U5fqrwNFm88J

" Go to the end and add a semicolon
inoremap <C-ENTER> <ESC>A;
inoremap O2P <ESC>A;

" Add a semicolon without moving the cursor and leaving insert mode
inoremap <C-S-ENTER> <ESC>maA;<ESC>`aa
inoremap O2R <ESC>maA;<ESC>`aa

" Add a new line below current line and go to it
inoremap <S-ENTER> <ESC>o
inoremap O2Q <ESC>o

" Add a semicolon to the end and a new line below and go to it
inoremap <D-ENTER> <ESC>A;<CR>
inoremap O2S <ESC>A;<CR>

" }}}
" Automatic commands ------------------------------------------------------- {{{

if has("autocmd") && !exists("autocommands_loaded")

	let autocommands_loaded = 1

	" Auto-source config files when changed
	autocmd BufWritePost .vimrc source %

	" Auto-source colorscheme when changed
	autocmd BufWritePost leya.vim source %

	" Add default content when creating PHP files
	autocmd BufNewFile *.php call setline(1, ['<?php', '', '']) | call setpos('.', [0, 3, 0, 0]) | startinsert

	" Add dashes as part of keyword in CSS files
	autocmd BufRead,BufNewFile CSS setlocal iskeyword+=-

	" Make vim see Vagrantfile as a ruby file
	autocmd BufRead,BufNewFile Vagrantfile setlocal filetype=ruby

	" Make vim see javascript template files as html
	autocmd BufNewFile,BufRead *.jst setlocal filetype=jst

	" Set textwidth for README file to 80 chars
	autocmd BufNewFile,BufRead README setlocal textwidth=78

	" Enable spellchecking in git commit messages
	autocmd BufNewFile,BufRead COMMIT_EDITMSG setlocal spell

	" Set textwidth to 80 when editing branch descriptions
	autocmd BufNewFile,BufRead BRANCH_DESCRIPTION setlocal textwidth=78

	" Up security for encrypted files
	autocmd BufReadPost * if &key != "" | set noswapfile nowritebackup viminfo= nobackup noshelltemp history=0 secure | endif

	" Don't want to fly around when writing e-mails
	autocmd FileType MAIL let g:AutoPairsFlyMode = 0
	autocmd FileType VIMWIKI setlocal tw=78

	" Make sure editing crontab works in OS X
	if has('mac')
		autocmd FileType crontab set nobackup nowritebackup
	endif

	" Add smarty gettext tags to surround
	autocmd FileType smarty let b:surround_103 = "{t}\r{/t}"

	" PHP
	autocmd FileType PHP let b:commentary_format = '// %s'

endif

" }}}
" Plugin configurations ------------------------------------------------------- {{{

" Matchit plugin comes with vim (see :e $VIMRUNTIME/macros/matchit.txt)
runtime macros/matchit.vim

" Auto-pairs
let g:AutoPairsShortcutFastWrap = '<C-S-F>'
let g:AutoPairsShortcutBackInsert = '<C-S-B>'
let g:AutoPairsFlyMode = 1
let g:AutoPairsCenterLine = 0

" Syntastic
let g:syntastic_auto_jump=2
let g:syntastic_auto_loc_list=1
let g:syntastic_php_phpmd_post_args="text  ~/.vim/bundle/0/phpmdrs.xml"
let g:syntastic_html_tidy_blocklevel_tags = ['a']
let g:syntastic_html_tidy_quiet_messages = { "level": "warnings"  }

" UltiSnips
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
let g:UltiSnipsSnippetDirectories = ["snips"]
let g:UltiSnipsNoPythonWarning = 1
let g:UltiSnipsSnippetsDir = "~/.vim/bundle/vim-marlun/snips"

" Neocomplete
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#use_vimproc = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#enable_auto_select = 1

" Echodoc
let g:echodoc_enable_at_startup = 1

" Niffler
let g:niffler_ignore_extensions = ['gif', 'jpg', 'png']
let g:niffler_ignore_dirs = ['cache', 'node_modules', 'templates_c', 'vendor']
map <leader>l :NifflerBuffer<cr>
map <leader>o :Niffler .<cr>
map <leader>t :NifflerTags %<cr>
map <leader>T :NifflerTags<cr>
map <leader>r :NifflerMRU<cr>

" VimWiki
let wiki = {'syntax': 'markdown', 'ext': '.md'}
if has('mac')
	let wiki.path = '~/Documents/VimWiki/'
else
	let wiki.path = '~/sync/Documents/VimWiki'
endif
let g:vimwiki_list = [wiki]
let g:vimwiki_hl_cb_checked = 1
let g:vimwiki_table_mappings = 0

" vim: foldmethod=marker
